Algoritmo "conversor"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 6/8/2022
Var
// Seção de Declarações das variáveis 
  din1, din2: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     Escreva("Quantos reais eu tenho? R$")
     Leia(din1)
     din2 <- din1/2.50
     Escreva("Posso ter US$", din2)

Fimalgoritmo