Algoritmo "creuza"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 6/8/2022
Var
// Seção de Declarações das variáveis 
    ano1, ano2,idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Em que ano nos estamos? ")
Leia(ano1)
Escreva("Em que ano eu nasci? ")
Leia(ano2)
idade <- ano1 - ano2
Escreva("Minha idade é ", idade)

Fimalgoritmo